services:
  fragments:
    container_name: fragments
    init: true
    build: .
    environment:
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=tests/.htpasswd
      - AUTH_STRATEGY=http
      - LOG_LEVEL=${LOG_LEVEL:-debug}

      - AWS_REGION=${AWS_REGION:-us-east-1}

      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000

      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-fragments}
      - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-test}
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
      - localstack

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory"]

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
